#!/bin/bash
#SBATCH --job-name fixed_kappa_1e8
#SBATCH --time 24:00:00
#SBATCH --nodes 22
#SBATCH --output janus_fixed_kappa_1e8.%J

mpirun -np 256 --bind-to core --map-by core python3 FC_fixed_kappa_1e8.py